import { useState } from "react";
import axios from "axios";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { BriefField, BriefSelect } from "@/components/builder/AdventureBrief";
import { formatCurrency } from "@/data/destinations";
import { QuoteEditor } from "@/components/QuoteEditor";
export const STAGES = ["new", "contacted", "proposal_sent", "confirmed", "lost", "archived"];
export const stageOf = (b) => b.status === "pending" ? "new" : b.status;
const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
export const InquiryCard = ({ inquiry: b, token, onSaved }) => {
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [workflow, setWorkflow] = useState({ status: stageOf(b), internal_notes: b.internal_notes || "", next_action: b.next_action || "", follow_up_date: b.follow_up_date || "", review_reason: b.review_reason || "", lost_reason: b.lost_reason || "" });
  const update = (key, value) => setWorkflow((p) => ({ ...p, [key]: value }));
  const save = async (event) => { event.preventDefault(); setBusy(true); try { await axios.patch(`${API}/bookings/${b.id}`, { ...workflow, follow_up_date: workflow.follow_up_date || null }, { headers: { Authorization: `Bearer ${token}` } }); toast.success("Inquiry updated"); onSaved(); } catch (e) { toast.error(typeof e.response?.data?.detail === "string" ? e.response.data.detail : "Could not save the inquiry"); } finally { setBusy(false); } };
  return <article data-testid={`booking-card-${b.id}`} className="bg-white border border-[#E6DFD5] rounded-xl p-5 sm:p-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="eyebrow">{b.reference || b.id} · {b.brief?.trip_type || "personal"}</p><h3 className="font-serif text-2xl mt-2">{b.package_name}</h3><p className="text-xs text-[#5C656E] mt-2">{b.contact.name} · {b.contact.email} · {b.travelers} travelers · {b.total_days} days</p></div><div className="text-sm"><span data-testid={`inquiry-stage-${b.id}`} className="rounded-full px-3 py-1 border border-[#E6DFD5] capitalize">{stageOf(b).replaceAll("_", " ")}</span><p data-testid={`inquiry-estimate-${b.id}`} className="mt-3 font-mono">{b.brief?.trip_type === "group" ? "Quote required" : `${formatCurrency(b.total_price)} example`}</p><p className="text-xs text-[#5C656E] mt-1">{b.created_at?.slice(0, 10)} · source: {b.brief?.source || "not recorded"}</p></div></div><Button data-testid={`booking-expand-${b.id}`} className="mt-4" variant="outline" size="sm" onClick={() => setOpen(!open)}>{open ? "Close workspace" : "Review inquiry"}</Button>
    {open && <div className="mt-6 space-y-6"><div className="grid sm:grid-cols-2 gap-5"><div><h4 className="font-medium text-sm mb-3">Traveler brief</h4><dl data-testid={`inquiry-brief-${b.id}`} className="text-xs space-y-2 text-[#5C656E]">{Object.entries(b.brief || {}).map(([key, value]) => <div key={key}><dt className="inline font-medium text-[#0B192C]">{key.replaceAll("_", " ")}: </dt><dd className="inline break-words">{Array.isArray(value) ? value.join(", ") || "Not specified" : value ?? "Not specified"}{key === "budget" && value != null ? " EUR" : ""}</dd></div>)}</dl><p className="text-xs mt-3">Preferred dates: {b.start_date?.slice(0, 10) || "Flexible"} → {b.end_date?.slice(0, 10) || "Flexible"}</p>{b.contact.phone && <p className="text-xs mt-2">Phone: {b.contact.phone}</p>}<p className="text-xs mt-3">Traveler notes: {b.contact.notes || "None"}</p></div><div><h4 className="font-medium text-sm mb-3">Route & original estimate</h4>{b.destinations.map((d) => <div key={d.id} className="mb-4 text-xs"><p className="font-medium">{d.name} · {d.days} days</p><p className="text-[#5C656E] mt-1">{d.accommodation}</p><p className="text-[#5C656E] mt-1">{d.activities.join(" · ") || "Experiences to discuss"}</p><p className="font-mono mt-1">{formatCurrency(d.subtotal)}</p></div>)}<p className="text-xs">Original subtotal {formatCurrency(b.subtotal)} · original tax {formatCurrency(b.tax)}</p><p className="planning-note mt-3">All availability, supplier scope, access, seasonal and suitability details require review. Multi-region transfers and transit nights are not confirmed. {b.unscheduled_activities?.map((a) => a.name).join("; ")}</p><details data-testid={`inquiry-timeline-${b.id}`}><summary data-testid={`inquiry-timeline-toggle-${b.id}`} className="text-sm cursor-pointer">Daily composition ({b.itinerary?.length || 0} days)</summary><ol className="mt-3 text-xs space-y-2">{b.itinerary?.map((day) => <li key={day.day}>Day {day.day} {day.date || ""} · {day.destination}: {day.activities.map((a) => a.name).join(" / ") || "Open time"}{day.overnight ? ` · Night: ${day.accommodation}` : ""}</li>)}</ol></details></div></div>
      <form data-testid={`workflow-form-${b.id}`} onSubmit={save} className="border-t border-[#E6DFD5] pt-5 space-y-4"><h4 className="font-medium text-sm">Team follow-up · private</h4><div className="grid sm:grid-cols-2 gap-4"><BriefField id={`booking-status-select-${b.id}`} label="Pipeline stage"><BriefSelect id={`booking-status-select-${b.id}`} value={workflow.status} onChange={(v) => update("status", v)} options={STAGES.map((s) => [s, s.replaceAll("_", " ")])} /></BriefField><BriefField id={`follow-up-${b.id}`} label="Follow-up date"><Input data-testid={`follow-up-${b.id}`} id={`follow-up-${b.id}`} type="date" value={workflow.follow_up_date} onChange={(e) => update("follow_up_date", e.target.value)} /></BriefField></div>{[["next_action", "Next action"], ["internal_notes", "Internal notes (never exported)"], ["review_reason", "Why further review is needed"], ["lost_reason", "Reason lost (required for Lost)"]].map(([key, label]) => <BriefField key={key} id={`${key}-${b.id}`} label={label}><Textarea data-testid={`${key}-${b.id}`} id={`${key}-${b.id}`} required={key === "lost_reason" && workflow.status === "lost"} value={workflow[key]} onChange={(e) => update(key, e.target.value)} /></BriefField>)}<Button data-testid={`workflow-save-${b.id}`} type="submit" disabled={busy}>{busy ? "Saving…" : "Save follow-up"}</Button></form>
      <QuoteEditor inquiry={b} token={token} onSaved={onSaved} />
    </div>}
  </article>;
};
