import { useLocale } from "@/hooks/useLocale";
import { destinations, formatCurrency } from "@/data/destinations";
import { activityName, regionName } from "@/data/outdooroots";
import { ArrowUp, ArrowDown } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { BriefSelect } from "@/components/builder/AdventureBrief";

export const RouteDesigner = ({ builder: b }) => {
  const { t, language } = useLocale();
  const dest = destinations.find((d) => d.id === b.activeTab);
  const selected = b.selectedDestinations.find((d) => d.id === b.activeTab);
  const group = b.brief.trip_type === "group";
  return <section id="route-designer" data-testid="route-designer" className="scroll-mt-24 mt-10">
    <p className="eyebrow mb-2">02 / {t("Choose your chapters", "Elige tus capítulos")}</p><h2 className="font-serif text-lg mb-4">{t("One country. Your own route.", "Un país. Tu propia ruta.")}</h2>
    <p className="text-xs text-[#5C656E] mb-6">{t("Reorder regions with the arrows. Day adventures and unfinished ideas are welcome. Transport between regions needs team review.", "Ordena las regiones con las flechas. Puedes crear una aventura de un día o enviar una idea incompleta. Los traslados requieren revisión.")}</p>
    <div className="flex flex-wrap gap-2 mb-6">{b.selectedDestinations.map((selection, i) => <div data-testid={`route-region-${selection.id}`} key={selection.id} className="flex items-center border border-[#E6DFD5] rounded-lg overflow-hidden bg-white">
      <button data-testid={`destination-tab-${selection.id}`} aria-pressed={b.activeTab === selection.id} onClick={() => b.setActiveTab(selection.id)} className={`px-3 py-3 text-xs transition-colors ${b.activeTab === selection.id ? "bg-[#0B192C] text-white" : "hover:bg-[#F6F2EB]"}`}>{regionName(selection.id, language)}{selection.days > 0 ? ` · ${selection.days}d` : ""}</button>
      <button aria-label={t("Move earlier", "Mover antes")} data-testid={`move-up-${selection.id}`} disabled={i === 0} onClick={() => b.moveDestination(selection.id, -1)} className="p-2 disabled:opacity-25 hover:bg-[#F6F2EB]"><ArrowUp className="w-3 h-3" /></button><button aria-label={t("Move later", "Mover después")} data-testid={`move-down-${selection.id}`} disabled={i === 4} onClick={() => b.moveDestination(selection.id, 1)} className="p-2 disabled:opacity-25 hover:bg-[#F6F2EB]"><ArrowDown className="w-3 h-3" /></button>
    </div>)}</div>
    <div data-testid={`destination-panel-${dest.id}`} className="border border-[#E6DFD5] rounded-xl overflow-hidden bg-white">
      <div className="relative bg-[#0B192C] px-6 py-8 text-white"><img src={dest.image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-25" /><div className="relative flex flex-wrap justify-between gap-5 items-center"><h3 className="font-serif text-3xl">{regionName(dest.id, language)}</h3><div className="flex gap-3 items-center"><Button data-testid={`days-minus-${dest.id}`} aria-label={t("Remove a day", "Quitar un día")} size="icon" variant="outline" className="bg-transparent" disabled={!selected.days} onClick={() => b.handleDaysChange(dest.id, selected.days - 1)}>−</Button><span data-testid={`days-count-${dest.id}`} className="font-mono text-sm">{selected.days} {t("days", "días")}</span><Button data-testid={`days-plus-${dest.id}`} aria-label={t("Add a day", "Añadir un día")} size="icon" variant="outline" className="bg-transparent" disabled={selected.days === 14} onClick={() => b.handleDaysChange(dest.id, selected.days + 1)}>+</Button></div></div></div>
      {!selected.days ? <div className="p-8 text-center"><p className="text-sm text-[#5C656E] mb-5">{t("Begin with a day outside, or stay a little longer.", "Empieza con un día al aire libre, o quédate un poco más.")}</p><Button data-testid={`quick-add-${dest.id}`} onClick={() => b.handleDaysChange(dest.id, 3)}>{t("Start with 3 days", "Empezar con 3 días")}</Button></div> : <div className="p-6 space-y-6">
        <div><p className="text-sm font-medium mb-3">{t("Experiences · illustrative rates", "Experiencias · tarifas ilustrativas")}</p><div className="space-y-2">{dest.activities.map((a) => <label key={a.id} htmlFor={`experience-${dest.id}-${a.id}`} data-testid={`activity-${dest.id}-${a.id}`} className="flex gap-3 items-start rounded-lg border border-[#E6DFD5] p-3 cursor-pointer hover:bg-[#F6F2EB] transition-colors"><Checkbox data-testid={`checkbox-${dest.id}-${a.id}`} id={`experience-${dest.id}-${a.id}`} className="mt-1" checked={selected.activities.includes(a.id)} onCheckedChange={() => b.handleActivityToggle(dest.id, a.id)} /><span className="flex-1 text-sm">{activityName(dest.id, a, language)}<span className="block text-xs text-[#5C656E] mt-1">{a.duration === 1 ? t("Full day", "Día completo") : t("Half day", "Medio día")} · {group || a.price == null ? t("Quote required", "Cotización requerida") : `${formatCurrency(a.price)} / ${a.id === "private-guide" ? t("group", "grupo") : t("person", "persona")}`}</span></span></label>)}</div></div>
        <div><label className="text-sm block mb-2" htmlFor={`accommodation-select-${dest.id}`}>{t("Proposed stay", "Estadía propuesta")} · <span data-testid={`nights-${dest.id}`}>{b.getNights(dest.id)} {t("nights", "noches")}</span></label><BriefSelect id={`accommodation-select-${dest.id}`} value={selected.accommodation || ""} onChange={(v) => b.handleAccommodationSelect(dest.id, v)} options={[["", t("Team recommendation · quote required", "Recomendación del equipo · cotización requerida")], ["custom", t("Local / simple / other stay · quote required", "Alojamiento local / sencillo / otro · cotización requerida")], ...dest.accommodations.map((a) => [a.id, `${a.name} · ${group ? t("quote required", "cotización requerida") : `${formatCurrency(a.price)} / ${t("person / night (sample)", "persona / noche (ejemplo)")}`}`])]} />{selected.accommodation === "custom" && <Input data-testid={`custom-accommodation-${dest.id}`} className="mt-3" maxLength={160} value={selected.customAccommodation} placeholder={t("Your stay preference", "Tu preferencia de alojamiento")} onChange={(e) => b.handleCustomAccommodation(dest.id, e.target.value)} />}<p className="text-xs text-[#5C656E] mt-3 leading-relaxed">{t("Named lodges are preferences, not partners or reserved inventory. Activity/lodge inclusions need review to avoid duplicate charges. Season, difficulty, age, access and acclimatization guidance: team review required.", "Los alojamientos son preferencias, no socios ni reservas. El equipo revisará las inclusiones para evitar cargos duplicados. Temporada, dificultad, edad, acceso y aclimatación: revisión del equipo requerida.")}</p></div>
      </div>}
    </div>
  </section>;
};
